import createClient from 'openapi-fetch';
import debug from 'debug';
import type { paths } from './api-schema'; // generated by openapi-typescript

const log = debug('api');
const client = createClient<paths>({
  baseUrl: process.env.UMI_APP_SERVER_URL
    ? process.env.UMI_APP_SERVER_URL
    : '/',
});

client.use({
  onResponse({ response }) {
    // log(response);
    // if (response.status >= 200) {
    //   notification.error({
    //     message: 'Error',
    //     description: response.statusText,
    //   });
    // }
  },
});

export { client };
